/* Q1. The management team wants to understand the overall financial performance of the company. 
 Calculate the total revenue generated from all completed orders using quantity ordered and selling price. */

-- Output Columns : total_revenue

SELECT SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM orderdetails od
JOIN orders o 
	ON od.orderNumber = o.orderNumber
WHERE o.status = 'Shipped';			-- Filter only completed (shipped) orders


/* Q2. Management wants to understand market presence across countries. Count customers in each country. */

-- Output Columns: country, total_customers

SELECT country,
	   COUNT(*) AS total_customers
FROM customers 
GROUP BY country
ORDER BY total_customers DESC;


/* Q3. The finance department wants to monitor how revenue changes over time. 
Calculate monthly revenue and display the trend year-wise and month-wise. */

-- Output Columns : order_year, order_month, monthly revenue

SELECT YEAR(o.orderDate) AS order_year,
	   MONTH(o.orderDate) AS order_month,
	   SUM(od.quantityOrdered * od.priceEach) AS monthly_revenue
FROM orders o 
JOIN orderdetails od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY order_year, 
		 order_month
ORDER BY order_year ASC, 
		 order_month ASC;


/* Q4. The company operates globally and wants to identify which countries contribute the most revenue.
Calculate total revenue generated by customers from each country. */

-- Output Columns: country, total_revenue

SELECT c.country,
	   SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM customers AS c
JOIN orders AS o
	ON c.customerNumber = o.customerNumber
JOIN orderDetails AS od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY country
ORDER BY total_revenue DESC;


/* Q5. The marketing team wants to categorize customers based on their spending behavior to identify high-value 
customers for loyalty programs and targeted campaigns. */

-- Output Columns: customerNumber, customerName, country, total_orders, total_revenue, customer_segment

SELECT c.customerNumber, 
	   c.customerName, 
       c.country, 
       COUNT(DISTINCT o.orderNumber) AS total_orders, 
       SUM(od.quantityOrdered * od.priceEach) AS total_revenue, 
       CASE
			WHEN SUM(od.quantityOrdered * od.priceEach) > 100000 THEN 'Platinum'
            WHEN SUM(od.quantityOrdered * od.priceEach) BETWEEN 50000 AND 100000 THEN 'Gold'
            ELSE 'Silver'
	   END AS customer_segment
FROM customers AS c
JOIN orders AS o
	ON c.customerNumber = o.customerNumber
JOIN orderdetails AS od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY c.customerNumber, 
	     c.customerName, 
         c.country
ORDER BY total_revenue DESC;


/* Q6. The sales team wants to re-engage inactive customers. 
Find customers who are registered in the system but have never placed an order. */

-- Output Columns: customerNumber, customerName, country 

SELECT c.customerNumber, 
	   c.customerName, 
       c.country
FROM customers c
WHERE c.customerNumber NOT IN (
		SELECT DISTINCT customerNumber 
        FROM orders 
        WHERE customerNumber IS NOT NULL
);


/* Q7. Product managers want to understand which products contribute most to company revenue. Calculate revenue generated by each product. */

-- Output Columns: productCode, productName, total_revenue 

SELECT p.productCode, 
	   p.productName,
       SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM products p
JOIN orderdetails od
	ON p.productCode = od.productCode
JOIN orders o 
	ON od.orderNumber = o.orderNumber
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY p.productCode, p.productName
ORDER BY total_revenue DESC;


/* Q8. Inventory planning depends on product demand.
Identify the top-selling products based on the total quantity sold and rank the products in descending order of quantity sold. */

-- Output Columns: productCode, productName, quantity_sold, product_rank

SELECT p.productCode,
	   p.productName,
       SUM(od.quantityOrdered) AS quantity_sold,
       DENSE_RANK() OVER(ORDER BY SUM(od.quantityOrdered) DESC) AS product_rank
FROM products p
JOIN orderDetails od
	ON p.productCode = od.productCode
JOIN orders o
	ON o.orderNumber = od.orderNumber 
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY p.productCode, p.productName
ORDER BY product_rank ASC;


/* Q9. Management wants to know which product categories are most profitable. Calculate total revenue generated by each product line.*/

-- Output Columns: productLine, total_revenue 

SELECT p.productLine,
	   SUM(quantityOrdered * priceEach) AS total_revenue
FROM products p
JOIN orderDetails od
	ON p.productCode = od.productCode
JOIN orders o
	ON o.orderNumber = od.orderNumber 
WHERE o.status = 'Shipped'			-- Filter only completed (shipped) orders
GROUP BY p.productLine
ORDER BY total_revenue DESC;


/* Q10. The sales director wants to evaluate employee performance. Calculate revenue generated by customers assigned to each sales representative.*/

-- Output Columns: employeeNumber, employeeName, jobTitle, total_revenue 

SELECT e.employeeNumber,
	   CONCAT(firstName,' ',lastName) AS employeeName,
       e.jobTitle,
       SUM(od.quantityOrdered * priceEach) AS total_revenue
FROM employees AS e
JOIN customers AS c
	ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders AS o
	ON o.customerNumber = c.customerNumber
JOIN orderDetails AS od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'
GROUP BY e.employeeNumber, 
		 e.firstName, 
		 e.lastName,
         e.jobTitle
ORDER BY total_revenue DESC;


/* Q11. Rank sales representatives based on the revenue generated from their assigned customers. */

-- Output Columns: employeeNumber, employeeName, total_revenue, sales_rank 

SELECT e.employeeNumber,
	   CONCAT(e.firstName, ' ', e.lastName) AS employeeName,
       SUM(od.quantityOrdered * od.priceEach) AS total_revenue,
       DENSE_RANK() OVER(ORDER BY SUM(od.quantityOrdered * od.priceEach) DESC) AS sales_rank
FROM employees AS e
JOIN customers AS c
	ON e.employeeNumber = c.salesRepEmployeeNumber		-- Connects employee to their assigned customers
JOIN orders AS o
	ON o.customerNumber = c.customerNumber		-- Connects customers to their placed orders
JOIN orderDetails AS od
	ON o.orderNumber = od.orderNumber		-- Connects orders to their pricing details
WHERE o.status = 'Shipped'		-- Filters for completed sales only
GROUP BY e.employeeNumber, e.firstName, e.lastName
ORDER BY sales_rank ASC;		-- Displays the top-performing employee (Rank 1) first


/* Q12. Regional managers want to compare office performance. Calculate total revenue generated by each office location. */

-- Output Columns: officeCode, city, country, total_customers, total_revenue

SELECT 
    ofc.officeCode,
    ofc.city,
    ofc.country,
    COUNT(DISTINCT c.customerNumber) AS total_customers,
    SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM offices ofc
JOIN employees e
	ON ofc.officeCode = e.officeCode
JOIN customers c
	ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o
	ON c.customerNumber = o.customerNumber
JOIN orderdetails od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'
GROUP BY 
    ofc.officeCode,
    ofc.city,
    ofc.country
ORDER BY total_revenue DESC;


/* Q13. The product team wants to identify star products in every category. 
Find the highest revenue-generating product within each product line. */

-- Output Columns: productLine, productName, total_revenue, rank

WITH ProductRevenue AS (
		SELECT p.productLine,
			   p.productName,
			   SUM(od.quantityOrdered * od.priceEach) AS total_revenue,
			   DENSE_RANK() OVER (PARTITION BY p.productLine 
								  ORDER BY SUM(od.quantityOrdered * od.priceEach) DESC) AS `rank`
    FROM products p
    JOIN orderdetails od 
		ON p.productCode = od.productCode
	JOIN orders o 
		ON o.orderNumber = od.orderNumber
	WHERE o.status = 'Shipped'
    GROUP BY p.productLine, 
			 p.productName)
SELECT 
    productLine,productName, total_revenue, `rank`
FROM 
    ProductRevenue
WHERE 
    `rank` = 1;


/* Q14. Regional sales managers want to identify their best customers. 
Rank customers by revenue within each country and find the top 3 customers for each country. */

-- Output Columns: country, customerName, total_revenue, country_rank

WITH CustomerRevenue AS (
	SELECT c.country,
		   c.customerName,
           SUM(od.quantityOrdered * od.priceEach) AS total_revenue,
           ROW_NUMBER() OVER(PARTITION BY c.country ORDER BY SUM(od.quantityOrdered * od.priceEach) DESC) AS country_rank
FROM customers c
JOIN orders o 
	ON c.customerNumber = o.customerNumber
JOIN orderdetails od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'
GROUP BY c.country,
		 c.customerNumber, -- Ensures acuracy if two customers shares a name
         c.customerName)

SELECT country,
	   customerName,
	   total_revenue,
	   country_rank
FROM CustomerRevenue
WHERE country_rank <=3
ORDER BY country ASC,
		 country_rank ASC;


/* Q15. Finance team wants month-over-month growth AND cumulative revenue 
so far this year, in one view. */

-- Output Columns: month, monthly_revenue, previous_month_revenue, growth_percentage, running_total_revenue

WITH MonthlyRevenue AS 
				(SELECT DATE_FORMAT(paymentDate, '%Y-%m') AS `month`,
					    SUM(amount) AS monthly_revenue
                FROM payments
                GROUP BY DATE_FORMAT(paymentDate, '%Y-%m')),

CalculatedGrowth AS 
				(SELECT `month`,
						monthly_revenue,
					    LAG(monthly_revenue, 1) OVER (ORDER BY `month`) AS previous_month_revenue,
                        SUM(monthly_revenue) OVER (ORDER BY `month` ROWS UNBOUNDED PRECEDING) AS running_total_revenue
                FROM MonthlyRevenue)

SELECT `month`,
	   monthly_revenue,
       previous_month_revenue,
       ROUND(((monthly_revenue - previous_month_revenue)/previous_month_revenue * 100),2) AS growth_percentage,
       running_total_revenue
FROM CalculatedGrowth
ORDER BY `month` ASC;


/* Q16. The company wants to identify customers who spend more per order. 
Calculate the average order value for each customer and rank them from highest to lowest. */

-- Output Columns: customerNumber, customerName, avg_order_value 

SELECT 
    c.customerNumber,
    c.customerName,
    ROUND(AVG(OrderTotals.order_total), 2) AS avg_order_value
FROM customers c
JOIN orders o 
	ON c.customerNumber = o.customerNumber
JOIN (
    -- This subquery calculates the total value for each individual order
    SELECT 
        orderNumber, 
        SUM(quantityOrdered * priceEach) AS order_total
    FROM 
        orderdetails
    GROUP BY 
        orderNumber
) AS OrderTotals 
	ON o.orderNumber = OrderTotals.orderNumber
WHERE o.status = 'Shipped'
GROUP BY 
    c.customerNumber,
    c.customerName
ORDER BY 
    avg_order_value DESC;


/* Q17. The sales team wants to identify loyal customers. Find customers who have placed more than 5 orders. */

-- Output Columns: customerNumber, customerName, total_orders

SELECT c.customerNumber, 
	   c.customerName, 
       COUNT(o.orderNumber) AS total_orders
FROM customers c
JOIN orders o 
	ON c.customerNumber = o.customerNumber
GROUP BY c.customerNumber, 
	     c.customerName
HAVING COUNT(o.orderNumber) > 5;


/* Q18. Identify how much each customer contributes to total company revenue. */

-- Output Columns: customerNumber, customerName, customer_revenue, revenue_percentage

SELECT c.customerNumber, 
	   c.customerName,
       SUM(od.quantityOrdered * od.priceEach) AS customer_revenue,
       ROUND(
			SUM(od.quantityOrdered * od.priceEach) * 100 
            / SUM(SUM(od.quantityOrdered * od.priceEach)) OVER(),
            2) AS revenue_percentage
FROM customers c 
JOIN orders o 
	ON c.customerNumber = o.customerNumber
JOIN orderdetails od
	ON o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'
GROUP BY c.customerNumber, c.customerName;


/* Q19. HR wants to visualize the reporting hierarchy of the sales organization. 
Display each employee alongside the name of their direct manager. */

-- Output Columns: employeeNumber, employeeName, jobTitle, managerName

SELECT e.employeeNumber,
	   CONCAT(e.firstName, ' ', e.lastName) AS employeeName,
       e.jobTitle,
       COALESCE(CONCAT(m.firstName, ' ', m.lastName), 'No Manager') AS managerName
FROM employees e 
LEFT JOIN employees m			-- Self-join: employees table joined to itself
	ON e.reportsTo = m.employeeNumber;


/* Q20. The customer success team wants to flag accounts that have had at least one 
cancelled order, so they can be prioritized for follow-up. */

-- Output Columns: customerNumber, customerName, country

SELECT c.customerNumber, 
	   c.customerName,
       c.country
FROM customers c 
WHERE EXISTS(
			SELECT 1
            FROM orders o 
            WHERE o.customerNumber = c.customerNumber
            AND o.status = 'Cancelled'
);


/* Q21. Marketing wants a single unified contact list combining both customers 
and employees, tagged by their role, for an upcoming company-wide mailer. */

-- Output Columns: full_name, email_or_phone, contact_type

SELECT 
    c.customerName AS full_name,
    c.phone AS email_or_phone,
    'Customer' AS contact_type
FROM customers c

UNION            -- Combines two result sets with the same column structure

SELECT 
    CONCAT(e.firstName, ' ', e.lastName) AS full_name,
    e.email AS email_or_phone,
    'Employee' AS contact_type
FROM employees e
ORDER BY full_name;


/* Q22. The reporting team wants a reusable, always-up-to-date summary of 
customer order performance without rerunning complex joins every time. */

-- Creates a VIEW: customer_order_summary

CREATE VIEW customer_order_summary AS
SELECT 
    c.customerNumber,
    c.customerName,
    c.country,
    COUNT(DISTINCT o.orderNumber) AS total_orders,
    SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM customers c
LEFT JOIN orders o 
    ON c.customerNumber = o.customerNumber
	AND o.status = 'Shipped'
LEFT JOIN orderdetails od 
    ON o.orderNumber = od.orderNumber
GROUP BY c.customerNumber, c.customerName, c.country;

-- Usage example:
SELECT * FROM customer_order_summary
ORDER BY total_revenue DESC;


/* Q23. Inventory managers want to identify "dead stock" — products that have 
never been ordered by any customer, so they can be reviewed for discontinuation. */

-- Output Columns: productCode, productName, productLine, quantityInStock

SELECT 
    p.productCode,
    p.productName,
    p.productLine,
    p.quantityInStock
FROM products p
LEFT JOIN orderdetails od 
    ON p.productCode = od.productCode
WHERE od.productCode IS NULL      -- Anti-join pattern: no matching order line exists
ORDER BY p.quantityInStock DESC;